name: Flujo_trabajo # nombre del flujo de trabajo
# evento que activa el flujo de trabajo 
on:
  push:
    branches:
      - main
# El flujo se ejecutará cada vez que haya un push a la rama main.

jobs:
  # Identificador del trabajo (job)
  example-job:
    # El job se ejecutará en Ubuntu último disponible
    runs-on: ubuntu-latest
    # Pasos del job
    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3
      # Uso del Personal Access Token para llamar a la API de GitHub
      - name: Use Personal Access Token
        run: |
          curl -H "Authorization: Bearer ${{ secrets.PAT_SECRET }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos

# GITHUB_TOKEN se genera automáticamente para cada ejecución del flujo
# y tiene permisos predeterminados para interactuar con el repositorio.
